### PR TITLE
Changes in OCMS

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Samy-33** [comment]
@kmunshi97, review this PR as soon as possible. High Priority.

**Comment by ghost** [comment]
@Samy-33 @kmunshi97  pls review

**Comment by ghost** [comment]
@Samy-33 @kmunshi97  Pls review ASAP.High Priority 
@Narosen  @AnimeshPandey @parascoder1  I have pushed the code but not reviewed yet .Pls pull from my fork if you want it.

**Comment by AnimeshPandey** [comment]
Okay, don't worry, Mayank.

**Comment by Samy-33** [comment]
I am merging this.

**Pull request merged**
