### PR TITLE
Helpers/decorators

### PR DESCRIPTION
**Pull request by Samy-33**
Added a decorator, which redirects the user to authentication page according to life of his session if he tries to access a critical_view.  
Improved README

### CODE REVIEW

**Review by arshadsid — COMMENTED** [review]
won't this refresh it after every 600 seconds even if there is some activity?

**Comment by Samy-33** [comment]
> won't this refresh it after every 600 seconds even if there is some activity?

@arshadsid, this is only for critical sections and yes you are right, that is in my mind. I am working on it.

**Review by arshadsid — APPROVED** [review]
Nice!

**Comment by pranjulps3** [comment]
we can do this just by sessions. I don't think we need a decorator for this.

**Comment by Samy-33** [comment]
Tell me how?

**Pull request merged**
