### PR TITLE
StudentComplaint , caretaker , supervisor , workers class added

### PR DESCRIPTION
**Pull request by shubhamy03**

### CODE REVIEW

**Review by arshadsid — CHANGES_REQUESTED** [review]
What is the need of supervisor table?
In worker table age is char and default value M?
Age is not required, sex cab be used instead.
You do not have to explicitly create id has they will be auto created.

**Review by arshadsid — CHANGES_REQUESTED** [review]
You can remove the id field from the other 2 tables as well, as that is redundant.

**Review by arshadsid — CHANGES_REQUESTED** [review]
Add assigned worker in StudentComplain table.

**Review by arshadsid — CHANGES_REQUESTED** [review]
White space between worker and student's complain classes.
Use ExtraInfo for staff and Student table has been shifted to academic_information.
Please update your repo to reflect the changes of academic_information.

**Comment by arshadsid** [comment]
Check flake8 and isort aswell

**Review by arshadsid — CHANGES_REQUESTED** [review]
Change import of student and staff from globals to extrainfo in globals and student in academic_information

**Review by arshadsid — APPROVED** [review]
Models are correct.

**Comment by Samy-33** [comment]
Good work @krishnanjali25 and @arshadsid

**Comment by shubhamy03** [comment]
thanks @arshadsid @Samy-33  for helping me

**Pull request merged**
